---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    local_vars_dir: "../../../edx-vars/local"
    secure_vars_dir: "../../../edx-vars/secure"
  vars_files:
    - "{{ local_vars_dir }}/common_sandbox.yml"
    - "{{ local_vars_dir }}/edxapp_sandbox.yml"
    - "{{ local_vars_dir }}/discern_sandbox.yml"
    - "{{ local_vars_dir }}/ora_sandbox.yml"
    - "{{ local_vars_dir }}/elasticsearch_sandbox.yml"
  roles:
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - ora
      - xqueue
      nginx_default_sites:
      - lms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - demo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - ora
    - discern
    - edx_ansible
